package UI;

public class UNI_Portada extends javax.swing.JPanel {
    
    /**
     * Creates new form UNI_Portada
     */
    public UNI_Portada() {
        initComponents();
        
        // load the image
        javax.swing.ImageIcon user_temp = new javax.swing.ImageIcon(getClass().getResource("/img/user-temp.png"));

        // extract only the img for manipulation
        java.awt.Image user_temp_img = user_temp.getImage();

        // create the img with custom dimensions
        java.awt.Image img_scaled = user_temp_img.getScaledInstance(150, 150, java.awt.Image.SCALE_SMOOTH);

        // create an icon box with the sacaled image
        javax.swing.ImageIcon final_ico = new javax.swing.ImageIcon(img_scaled);

        // display the ico in the panel (portana-uni)
        temp_icon.setIcon(final_ico);
        temp_icon1.setIcon(final_ico);
        temp_icon2.setIcon(final_ico);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        portada_uni = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        temp_icon = new javax.swing.JLabel();
        temp_icon1 = new javax.swing.JLabel();
        temp_icon2 = new javax.swing.JLabel();
        carne = new javax.swing.JLabel();
        name1 = new javax.swing.JLabel();
        carne1 = new javax.swing.JLabel();
        name2 = new javax.swing.JLabel();
        carne2 = new javax.swing.JLabel();
        name3 = new javax.swing.JLabel();

        portada_uni.setBackground(new java.awt.Color(8, 24, 73));
        portada_uni.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        portada_uni.setForeground(new java.awt.Color(8, 24, 73));
        portada_uni.setFocusCycleRoot(true);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(236, 233, 210));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Universidad Nacional de Ingeniería");
        jLabel1.setMaximumSize(new java.awt.Dimension(228, 18));

        carne.setFont(new java.awt.Font("sansserif", 2, 18)); // NOI18N
        carne.setForeground(new java.awt.Color(236, 233, 210));
        carne.setText("2025-1905U");

        name1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        name1.setForeground(new java.awt.Color(236, 233, 210));
        name1.setText("Janelly Romero");

        carne1.setFont(new java.awt.Font("sansserif", 2, 18)); // NOI18N
        carne1.setForeground(new java.awt.Color(236, 233, 210));
        carne1.setText("2025-2560U");

        name2.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        name2.setForeground(new java.awt.Color(236, 233, 210));
        name2.setText("Moises Alemán");

        carne2.setFont(new java.awt.Font("sansserif", 2, 18)); // NOI18N
        carne2.setForeground(new java.awt.Color(236, 233, 210));
        carne2.setText("2025-2560U");

        name3.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        name3.setForeground(new java.awt.Color(236, 233, 210));
        name3.setText("Christopher Cisneros");

        javax.swing.GroupLayout portada_uniLayout = new javax.swing.GroupLayout(portada_uni);
        portada_uni.setLayout(portada_uniLayout);
        portada_uniLayout.setHorizontalGroup(
            portada_uniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, portada_uniLayout.createSequentialGroup()
                .addContainerGap(264, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(216, 216, 216))
            .addGroup(portada_uniLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(portada_uniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(portada_uniLayout.createSequentialGroup()
                        .addComponent(temp_icon1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(temp_icon2, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(temp_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(portada_uniLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(portada_uniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(name1)
                            .addComponent(carne))
                        .addGap(189, 189, 189)
                        .addGroup(portada_uniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(name2)
                            .addComponent(carne1))
                        .addGap(185, 185, 185)
                        .addGroup(portada_uniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(name3)
                            .addComponent(carne2))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        portada_uniLayout.setVerticalGroup(
            portada_uniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(portada_uniLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                .addGroup(portada_uniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(temp_icon2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(temp_icon1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(temp_icon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(portada_uniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(portada_uniLayout.createSequentialGroup()
                        .addGroup(portada_uniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(name2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(name1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(carne, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(name3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(portada_uniLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(portada_uniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(carne1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(carne2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(99, 99, 99))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(portada_uni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(portada_uni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel carne;
    private javax.swing.JLabel carne1;
    private javax.swing.JLabel carne2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel name1;
    private javax.swing.JLabel name2;
    private javax.swing.JLabel name3;
    private javax.swing.JPanel portada_uni;
    private javax.swing.JLabel temp_icon;
    private javax.swing.JLabel temp_icon1;
    private javax.swing.JLabel temp_icon2;
    // End of variables declaration//GEN-END:variables
}
